### ISSUE TITLE
大佬留个联系方式啊，看到你博客里面的mybatis数据权限受到很大帮助

### ISSUE THREAD

**Issue by stan9333** [Ozipin/Ozipin.github.io#1]
想问下buildDataAuthCondition函数的实现，谢谢~
博客里应该是漏掉了

**Comment by stan9333** [comment]
http://121.37.242.184/2022/01/03/%E5%9F%BA%E4%BA%8EMybatis%E7%9A%84%E6%95%B0%E6%8D%AE%E6%9D%83%E9%99%90%E7%9A%84%E5%AE%9E%E7%8E%B0/

**Comment by Ozipin** [comment]
> 想问下buildDataAuthCondition函数的实现，谢谢~ 博客里应该是漏掉了

相关内容由于涉及到公司的一些业务，所以就没贴出，主要思路就是根据字段名拼凑出权限相关查询条件，

**Comment by Ozipin** [comment]
public String buildDataAuthCondition(@NonNull String tableName, @NonNull UserDataAuthInfoResp curUserDataAuthInfo) {
        List<String> tempList = Lists.newArrayListWithExpectedSize(3);
        if (StringUtils.isNotBlank(this.getBgColumnName())
            && CollectionUtils.isNotEmpty(curUserDataAuthInfo.getBgCodes())) {
            tempList.add(String.format("%s.%s in ('%s')", tableName, this.getBgColumnName(),
                String.join("','", curUserDataAuthInfo.getBgCodes())));
        }
        if (StringUtils.isNotBlank(this.getAreaColumnName())
            && CollectionUtils.isNotEmpty(curUserDataAuthInfo.getAreaCodes())) {
            ......
        }
        if (StringUtils.isNotBlank(this.getNetColumnName())
            && CollectionUtils.isNotEmpty(curUserDataAuthInfo.getNetCodes())) {
            ......
        }
        return String.format("( %s )", String.join(" or ", tempList));
    }
